[toolchain]
# Needed nightly features:
# - cargo `Z-bindeps` to build and embed preload shared libraries as dependencies of fspy
# - `command_resolved_envs` to pass configured commands through fspy and PTY test helpers
# - `windows_process_extensions_main_thread_handle` to get the main thread handle for Detours injection
channel = "nightly-2026-06-07"
profile = "default"
