//! Embedded web UI assets (generated by `build.rs` from `ui/dist`).

include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));

/// Look up an embedded asset by its dist-relative path (no leading slash).
#[must_use]
pub fn get(path: &str) -> Option<&'static [u8]> {
    ASSETS.iter().find(|(p, _)| *p == path).map(|&(_, bytes)| bytes)
}

/// A guessed `Content-Type` for a dist-relative path, by extension.
#[must_use]
pub fn content_type(path: &str) -> &'static str {
    match path.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("js" | "mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json" | "map") => "application/json; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        Some("ttf") => "font/ttf",
        Some("png") => "image/png",
        Some("ico") => "image/x-icon",
        _ => "application/octet-stream",
    }
}
