[package]
name = "embedded_artifact"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
const_format = { workspace = true, features = ["fmt"] }
rand = { workspace = true }
xxhash-rust = { workspace = true, features = ["const_xxh3"] }

[lints]
workspace = true

[lib]
doctest = false
