[package]
name = "fspy_seccomp_ptrace"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[target.'cfg(target_os = "linux")'.dependencies]
wincode = { workspace = true, features = ["derive"] }
libc = { workspace = true }
nix = { workspace = true, features = ["process", "fs", "ptrace", "uio"] }
rustc-hash = { workspace = true }
seccompiler = { workspace = true }
syscalls = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["net", "process", "io-util", "rt", "sync"] }
tracing = { workspace = true }
tempfile = { workspace = true }
futures-util = { workspace = true }

[target.'cfg(target_os = "linux")'.dev-dependencies]
assertables = { workspace = true }
futures-util = { workspace = true }
nix = { workspace = true, features = ["fs"] }
test-log = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"] }

[features]
supervisor = []
target = []

[lints]
workspace = true

[lib]
test = false
doctest = false

[[test]]
name = "arg_types"
required-features = ["supervisor", "target"]
